spring:
  application:
    name: car-service
  redis:
    host: redis         # Docker container name of Redis
    port: 6379
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
